### PR TITLE
Redshift Integration

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
I have implemented the new integration for Redshift. After some initial testing, it looks to be working as expected. However, similar to the Databricks handler, I believe this will need it's own dialect for the renderer?
@ea-rus Do you think you can help with this?

For now, I have added the following,
```
from sqlalchemy_redshift import RedshiftDialect

def query(self, query: ASTNode) -> StatusResponse:
    """
    Receive query as AST (abstract syntax tree) and act upon it somehow.
    Args:
        query (ASTNode): sql query represented as AST. May be any kind
            of query: SELECT, INTSERT, DELETE, etc
    Returns:
        HandlerResponse
    """
    renderer = SqlalchemyRender(RedshiftDialect)
    query_str = renderer.get_string(query, with_failback=True)
    return self.native_query(query_str)
```
I have commented out these lines of code, so let me know if I can just uncomment it or if I need to make any changes.

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
Understood. Does that mean what I have done is correct?
Do we already have `sqlalchemy_redshift`?

**Comment by ea-rus** [comment]
Yes, code in comment above looks correct. 
Did you test it?  Was there some problems with rendering?

**Comment by MinuraPunchihewa** [comment]
@ea-rus I seem to be getting the error given below,
`cannot import name 'RedshiftDialect' from 'sqlalchemy_redshift'`

Do you know how exactly I should be using this?

**Comment by ea-rus** [comment]
I looked at sources and I think:
```
from redshift_sqlalchemy import dialect
dialect.RedshiftDialect <- it is here
```

**Comment by MinuraPunchihewa** [comment]
@ea-rus Thank you! Let me test this out and get back to you.

**Comment by MinuraPunchihewa** [comment]
@ea-rus The import issue seems to be resolved now, but I am now getting this error in mindsdb_sql,
```
self.dialect = dialects[dialect_name].dialect()
KeyError: <class 'sqlalchemy_redshift.dialect.RedshiftDialect_psycopg2'>
```

**Comment by ea-rus** [comment]
It looks like you are using  old version of mindsdb_sql. 
At least this line is from old version
self.dialect = dialects[dialect_name].dialect()

**Comment by MinuraPunchihewa** [comment]
@ea-rus Sorry, my mistake.
How can I use the latest version? 

Can I just issue,
`pip install mindsdb-sql --upgrade`

Or do I need to install it the way you have outlined in one of the previous pull requests I made? Like this, I mean,
`pip install git+ssh://git@github.com/mindsdb/mindsdb_sql.git@staging`

I cannot seem to use the second method though. This is the error I encounter,
```
Collecting git+ssh://****@github.com/mindsdb/mindsdb_sql.git@staging
  Cloning ssh://****@github.com/mindsdb/mindsdb_sql.git (to revision staging) to c:\users\minurap\appdata\local\temp\pip-req-build-d9c3704j
  Running command git clone -q 'ssh://****@github.com/mindsdb/mindsdb_sql.git' 'C:\Users\minurap\AppData\Local\Temp\pip-req-build-d9c3704j'
  Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
WARNING: Discarding git+ssh://****@github.com/mindsdb/mindsdb_sql.git@staging. Command errored out with exit status 128: git clone -q 'ssh://****@github.com/mindsdb/mindsdb_sql.git' 'C:\Users\minurap\AppData\Local\Temp\pip-req-build-d9c3704j' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/mindsdb/mindsdb_sql.git' 'C:\Users\minurap\AppData\Local\Temp\pip-req-build-d9c3704j' Check the logs for full command output.
```

**Comment by ZoranPandovski** [comment]
@MinuraPunchihewa `pip install mindsdb-sql --upgrade` should work.

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Upgrading `mindsdb-sql` worked for me and now it's running fine. Before getting it to run successfully, I had to resolve one error though. This was in mindsdb/utilities/json_encoder. 

From the following,
```
        if isinstance(obj, np.float16) or isinstance(obj, np.float32) or isinstance(obj, np.float64) or isinstance(obj, np.float128) or isinstance(obj, Decimal):
            return float(obj)
```

I had to remove the condition `isinstance(obj, np.float128)`, because I was getting this error,
`AttributeError: module 'numpy' has no attribute 'float128'`

If this change is fine, this should be OK to merge now.

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
@MinuraPunchihewa 🎉 🥳

**Pull request merged**
